# Generated by Django 5.1.5 on 2025-05-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
