# Generated by Django 5.1.5 on 2025-05-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk1', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('wallet', 'Wallet')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
