# Generated by Django 5.1.5 on 2025-06-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk1', '0009_remove_staff_login_email_staff_login_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_login',
            name='user_id',
            field=models.CharField(default='temp_user', max_length=50),
        ),
    ]
