# Generated by Django 5.1.5 on 2025-06-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk1', '0010_alter_staff_login_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('stockout', models.BooleanField(default=False)),
            ],
        ),
    ]
