# Generated by Django 5.1.5 on 2025-06-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk1', '0011_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='food_images/')),
                ('stock_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
