# Generated by Django 5.1.5 on 2025-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk1', '0012_fooditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.RemoveField(
            model_name='staff_login',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff_login',
            name='phone',
        ),
        migrations.AlterField(
            model_name='staff_login',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
