# Generated by Django 5.1.5 on 2025-06-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk1', '0013_delete_menuitem_remove_staff_login_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='yemani_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YemaniFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='food_images/')),
                ('stock_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
